# Generated by Django 4.2.11 on 2026-03-03 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.CharField(db_index=True, help_text='Unique identifier for the ARGO float', max_length=20, unique=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='First time this float was observed')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this float was observed')),
            ],
            options={
                'db_table': 'floats',
                'ordering': ['platform_number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude in degrees (-90 to 90)')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude in degrees (-180 to 180)')),
                ('profile_time', models.DateTimeField(db_index=True, help_text='Time of the profile measurement')),
                ('float', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ingestion.float')),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-profile_time'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path or URL of the processed file', max_length=500, unique=True)),
                ('file_name', models.CharField(help_text='Name of the processed file', max_length=255)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the file was processed')),
                ('records_inserted', models.IntegerField(default=0, help_text='Number of records inserted from this file')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'db_table': 'processed_files',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['file_path'], name='processed_f_file_pa_114433_idx'), models.Index(fields=['processed_at'], name='processed_f_process_ee05a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(blank=True, help_text='Pressure in decibars', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in degrees Celsius', null=True)),
                ('salinity', models.FloatField(blank=True, help_text='Practical salinity units (PSU)', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='ingestion.profile')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['pressure'],
            },
        ),
        migrations.AddIndex(
            model_name='float',
            index=models.Index(fields=['platform_number'], name='floats_platfor_07389d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['profile_time'], name='profiles_profile_3971fc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='profiles_latitud_0ac0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['float', 'profile_time'], name='profiles_float_i_a3e7cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('float', 'profile_time')},
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['profile'], name='measurement_profile_342911_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['pressure'], name='measurement_pressur_67e84b_idx'),
        ),
    ]
